export enum RequirementKeysInput {
  name = 'name',
  female = 'female',
  quantity = 'quantity',
  femaleAdvance = 'femaleAdvance',
  male = 'male',
  maleAdvance = 'maleAdvance',
  adultLittle = 'adultLittle',
  adultLittleAdvance = 'adultLittleAdvance',
  adult = 'adult',
  adultAdvance = 'adultAdvance',
  adultUpper = 'adultUpper',
  adultUpperAdvance = 'adultUpperAdvance',
  surveyId = 'surveyId',
}
